llm:
  llm-server: remote # 可选项: local, remote
  chatglm-api: 123456 # 填写成自己的 API 即可
  prompt: /home/orangepi/Code/Python/llm/cfg/prompt.txt
  llama-path: /home/orangepi/Code/Python/llm/DeepSeek-R1-Distill-Qwen-1.5B-Q8_0.gguf
